print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? £"))
tip = float(input("How much tip would you like to give as a percentage? 10, 12 or 15? "))
people = int(input("How many people to split the bill? "))
pay_per_person = round((bill * (tip / 100) + bill) / people, 2)
print(f"Each person should pay: £{pay_per_person}")